#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-BIP
version:      0.51
version_from: lib/Text/BIP.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
